### home page
GET  http://localhost:5000/ HTTP/1.1


### sign up
POST http://localhost:5000/register HTTP/1.1
content-type: application/json

{
    "user": "sample_user8",
    "pwd": "wed123"
}

### login

POST http://localhost:5000/auth HTTP/1.1
content-type: application/json

{
    "user": "sample_user8",
    "pwd": "wed123"
}

### refresh access token
POST http://localhost:5000/refresh Content-Type: application/json

### UP: send refresh token in cookie

### cookie

### request a service that requires login by sending access token

GET http://localhost:5000/posts Authorization: Bearer token

### logout

DELETE http://localhost:5000/logout Content-Type: application/json

###


